# Generated by Django 5.0.2 on 2024-03-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('paiement', models.CharField(max_length=100)),
                ('code_tva', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'facture',
                'verbose_name_plural': 'factures',
            },
        ),
    ]
