# Generated by Django 5.0.3 on 2024-04-01 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactureVente',
            fields=[
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
                ('date_comptabilisation', models.DateField(blank=True, null=True)),
                ('date_decheance', models.DateField(blank=True, null=True)),
                ('facture_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
    ]
