# Generated by Django 5.0.3 on 2024-05-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiements', '0003_paiement_montant_partiel_alter_payer_creer_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='montant_partiel',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Payer',
        ),
    ]
