# Generated by Django 5.0.3 on 2024-05-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avoirs', '0001_initial'),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avoir',
            name='commande_ligne',
        ),
        migrations.AddField(
            model_name='avoir',
            name='commande_ligne',
            field=models.ManyToManyField(related_name='avoirs', to='commandes.commande_ligne'),
        ),
    ]
