# Generated by Django 5.0.3 on 2024-03-28 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise', models.CharField(choices=[('EUR', 'EUR (EUR)'), ('GBP', 'GBP (GBP)'), ('USD', 'USD (USD)')], max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='dossier_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='devise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.device'),
        ),
    ]
