# Generated by Django 5.0.3 on 2024-06-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code_client',
            field=models.CharField(default='C0001', max_length=20),
        ),
    ]
