# Generated by Django 5.0.3 on 2024-04-28 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commande_ligne', '0001_initial'),
        ('commandes', '0001_initial'),
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande_ligne',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_lignes', to='commandes.commande'),
        ),
        migrations.AddField(
            model_name='commande_ligne',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commande_lignes', to='produits.produit'),
        ),
        migrations.AlterUniqueTogether(
            name='commande_ligne',
            unique_together={('commande', 'produit')},
        ),
    ]
